name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-genesis:
    name: Check genesis validity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'

      - name: Check genesis validity ✅
        run: |
          pip3 install -r scripts/requirements.txt
          python scripts/check-genesis.py "$GITHUB_WORKSPACE/genesis.json"

  check-gentxs:
    name: Check gentxs validity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'

      - name: Check gentxs validity ✅
        run: |
          pip3 install -r scripts/requirements.txt
          python scripts/check-gentx.py "$GITHUB_WORKSPACE/gentxs"

  collect-genesis:
    name: Collect genesis test
    runs-on: ubuntu-latest
    needs:
      - check-gentxs
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Canine 💿
        run: |
          wget -O canine https://github.com/JackalLabs/canine-chain/releases/download/v0.0.0-alpha.2/canined-Linux
          chmod +x ./canine
          ./canine init test

      - name: Collect genesis transactions 📮
        run: |
          cp genesis.json ~/.canine/config/genesis.json
          cp -a gentxs/. ~/.canine/config/gentx/
          ./canine collect-gentxs

      - name: Validate genesis ✅
        run: |
          ./canine validate-genesis ~/.canine/config/genesis.json

      - name: Start chain ⛓
        run: |
          ./canine start > output.txt 2>&1 &

      - name: Test liveness ✅
        run: |
          sleep 30
          if [[ $(cat output.txt | grep "Reconnecting to peer") ]]; then
            echo "Chain starting"
            exit 0
          else
            echo "Chain not started"
            exit 1
          fi
