name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  check-gentxs:
    name: Check gentxs validity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'

      - name: Check gentxs validity ✅
        run: |
          pip3 install -r scripts/requirements.txt
          python scripts/check-gentx.py "$GITHUB_WORKSPACE/gentxs"
      - uses: actions/upload-artifact@v3
        with:
          name: genesis/genesis.json
          path: genesis/genesis.json

        

  collect-genesis:
    name: Collect genesis test
    runs-on: ubuntu-latest
    needs:
      - check-gentxs
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Download Canine 💿
        run: |
          git clone https://github.com/JackalLabs/canine-chain.git
      - name: Install Canine 💿
        working-directory: ./canine-chain
        run: |
          git checkout woof-4
          make build
          ./build/canined init test
      - name: Collect genesis transactions 📮
        run: |
          cp genesis/genesis.json ~/.canine/config/genesis.json
          cp -a gentxs/. ~/.canine/config/gentx/
          ./canine-chain/build/canined collect-gentxs

      - name: Validate genesis ✅
        run: |
          ./canine-chain/build/canined validate-genesis ~/.canine/config/genesis.json

      - name: Start chain ⛓
        run: |
          ./canine-chain/build/canined start > output.txt 2>&1 &

      - name: Test liveness ✅
        run: |
          sleep 30
          if [[ $(cat output.txt | grep "Reconnecting to peer") ]]; then
            echo "Chain starting"
            exit 0
          else
            echo "Chain not started"
            exit 1
          fi
